def menu_nasgor():
    print("1. Nasi Goreng Original")
    print("2. Nasi Goreng Bule")
    print("3. Nasi Goreng Bakso")
    print("4. Nasi Goreng Ayam")
    print("5. Nasi Goreng Sosis")
    print("6. Nasi Goreng Spesial")
    print("7. Magelangan Original")
    print("8. Magelangan Bakso")
    print("9. Magelangan Sosis")
    print("10. Magelangan Ayam")
    print("11. Magelangan Spesial")

def menu_lauk():
    print("1. Nasi Telur Dadar")
    print("2. Nasi Telur Balado")
    print("3. Nasi Ayam Opor")
    print("4. Nasi Ayam Balado")
    print("5. Nasi Ayam Kentaki")
    print("6. Nasi Ayam Geprek")
    print("7. Nasi Ati Ampela")
    print("8. Nasi Sayur")
    print("9. Nasi Sarden")
    print("10. Nasi Orak Arik Original")
    print("11. Nasi Orak Arik Bakso")
    print("12. Nasi Orak Arik Sosis")
    print("13. Nasi Orak Arik Ayam")
    print("14. Nasi Orak Arik Spesial")

def menu_mie():
    print("1. Indomie Tante Goreng/Kuah")
    print("2. Indomie Intel Goreng/Kuah")
    print("3. Mie Dokdok Original")
    print("4. Mie Dokdok Bakso")
    print("5. Mie Dokdok Sosis")
    print("6. Mie Dokdok Ayam")
    print("7. Mie Dokdok Spesial")
    print("8. Mie Tektek Original")
    print("9. Mie Tektek Bakso")
    print("10. Mie TekTek Sosis")
    print("11. Mie Tektek Ayam")
    print("12. Mie Tektek Spesial")

def menu_bubur():
    print("1. Bubur Kacang Ijo")
    print("2. Bubur Ketan Hitam")
    print("3. Bubur Campur")
    print("4. Bubur Ayam")

def menu_minum():
    print("1. Es/Hangat Teh")
    print("2. Es/Hangat Jeruk")
    print("3. Es/Hangat Lemon Tea")
    print("4. Es/Hangat Beng-Beng")
    print("5. Es/Hangat Goodday")
    print("6. Es/Hangat Chocolatos")
    print("7. Es/Hangat Hilo")
    print("8. Es/Hangat Nutrisari")
    print("9. Es Soda Gembira")
    print("10. Es Kuku Bima/Extra Joss")
    print("11. Kopi Hitam")
    print("12. Es/Hangat Susu")
    print("13. Es/Hangat Sirup")
    print("14. Adem Sari")
    print("15. Air Es")

def menu_snack():
    print("1. Mendoan ")
    print("2. Bakwan")
    print("3. Pisang Goreng")
    print("4. Tahu Isi")
    print("5. Bakso")
    print("6. Sosis")
    print("7. French Fries")
    print("8. Mix Platter")